config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  get 'home/about' => 'home#about', as: 'about'
  resources :books, only:[:create, :index, :show, :edit, :destroy,:update] do
    resource :favorites, only:[:create, :destroy]
  resources :book_comments, only:[:create, :destroy]
  end
  resources :users, only:[:new, :create, :index, :show, :edit, :update,:destroy] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence:true
  validates :body, presence:true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence:true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  #1:Nの関係
  belongs_to :user
  belongs_to :book

  #「１ユーザー」「１記事」に対して「１いいね」
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_one_attached :profile_image


  validates :name, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  #いいねをしているかしていないかの判定を付ける
  def already_favorited?(book)
    self.favorites.exists?(book_id: book.id)
  end

  #ユーザーのフォロー追加
  def follow(user_id)
    follower.ceate(followed_id: :user_id)
  end
  #ユーザーのフォロー外す
  def unfollow(user_id)
    follower.find_by(followed_id: :user_id).destroy
  end
  #フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize: size).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
     user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
     root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comments_params)
    comment.book_id = book.id
    comment.save
    redirect_to request.referer
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to request.referer
  end

  private

  def book_comments_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @user = current_user
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
  if @new_book.save
     flash[:notice] = "You have created book successfully."
     redirect_to book_path(@new_book)
  else
      @books = Book.all
      render :index
  end
  end

  def show
    @user = current_user
    @new_book = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @favorite = Favorite.new
  end

  def index
    @new_book = Book.new
    @books = Book.all
    @user = current_user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    flash[:notice] = "Book was successfully destroyed."
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = current_user.favorites.create(book_id: params[:book_id])
    redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:id])
    @favorite = current_user.favorite.find_by(book_id: @book.id)
    @favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only:[:edit, :update]

  def new
   @book = Book.new
  end

  def show
    @new_book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
    @following_users = @user.following_user
    @follower_users = @user.follower_user
  end

  def create
    @user = User.new(user_params)
  if @user.save
    redirect_to user_path
  else
    render new_user_registration_path
  end
  end

  def index
    @users = User.all
    @new_book = Book.new
    @books = Book.all
    @user = current_user
    @following_users = @user.following_user
    @follower_users = @user.follower_user
  end

  def edit
     @user = current_user
  end

  def update
    @user = User.find(params[:id])
    @book = Book.new
    @user.update(user_params)
    if @user.save
      flash[:notice] = "Welcome! You have signed up successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.following_user
  end

  def followers
    user = User.find(params[:id])
    @users = user.follower_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
    <div class="row">
      <div class="col-8 mx-auto">
        <h1 class="mt-5 mb-4">Editing Book</h1>
        <div class="text-danger">
        <% if @book.errors.any? %>
          <%= @book.errors.count %>errors prohibited this obj from being saved:
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        </div>


        <%= form_with model: @book, method: :patch, local:true do |f| %>
        <div class="form-group">
        <label>Title</label>
        <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
        <label>Opinion</label>
        <%= f.text_area :body, class: "form-control" %>
        </div>

        <%= f.submit 'Update Book', class: "btn btn-success mb-2"  %>
        <% end %>

        <span>
        <%=link_to 'Show', book_path %>
        </span>
          |
        <span>
        <%=link_to 'Back', books_path %>
        </span>
      <div>
    </div>
</div>

app/views/books/index.html.erb
<!--部分テンプレート-->
<%= render 'layouts/compile', new_book: @new_book, user: @user %>

<div class="col-md-8 offset-md-1">
<h2 class="mt-5">Books</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Opinion</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user_id) do %>
          <%= image_tag book.user.get_profile_image('50x50') %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
        <td>
          <% if current_user.already_favorited?(book) %>
          <%= link_to "♥",book_favorites_path(book), method: :delete %>
          <% else %>
          <%= link_to "♥",book_favorites_path(book), method: :post %>
          <% end %>
          <%= book.favorites.count%>
        </td>
        <td>コメント数:<%= book.book_comments.count %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<!--部分テンプレート-->
<%= render 'layouts/compile', new_book: @new_book, user: @book.user %>

<div class="col-md-8 offset-md-1">
    <h2 class="mt-5">Book detail</h2>
      <table class="table table-hover">
        <tbody>
          <tr>
            <td><%= image_tag @book.user.get_profile_image('50x50') %><br>
            <%= link_to @book.user.name, user_path(@book.user) %></td>
            <td><%= link_to @book.title, books_path %></td>
            <td><%= @book.body %></td>
            <td>
              <% if current_user.already_favorited?(@book) %>
              <%= link_to "♥", book_favorites_path(@book), method: :delete %>
              <% else %>
              <%= link_to "♥", book_favorites_path(@book), method: :post %>
              <% end %>
              <%= @book.favorites.count %>
            </td>
            <td>コメント数:<%= @book.book_comments.count %></td>
            <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book.id), class: "btn btn-success"%></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-danger"%></td>
            <% end %>
          </tr>
        </tbody>
      </table>

      <div>
        <% @book.book_comments.each do |book_comment| %>
        <div class="row ml-2">
        <p class="ml-1 mr-2"><%= image_tag book_comment.user.get_profile_image("100x100") %></p>
        <%= book_comment.comment %>
        <% if book_comment.user == current_user %>
        <span><%= link_to "Destroy", book_book_comment_path(book_comment.book,book_comment), method: :delete, class: "btn btn-danger btn-sm ml-2" %>
        </span>
        <% end %>
        </div>
        <%= book_comment.user.name %>
        <% end %>
      </div>

      <div>
        <%= form_with model: [@book, @book_comment], local: true do |f| %>
        <%= f.text_area :comment, row: '3', size: '50x3', placeholder: 'コメントをここに' %><br>
        <%= f.submit "送信する", class: "btn bet-sm btn-secondary" %>
        <% end %>
      </div>
</div>
</div>
</div>

app/views/home/about.html.erb
<div class="container">
    <div class="row">
        <h1 class="mx-auto pm-3 mt-5">Welcome to <i class="fas fa-book"></i><strong>Bookers!</strong></h1>
    </div>
</div>

app/views/home/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-xl-6">
      <h1 class="m-0 mt-4">Welcome to<i class="fas fa-book"></i><strong>Bookers!</strong></h1>
      　<p class="m-0"><strong>In<i class="fas fa-book"></i>Bookers,</strong></p>
      　<p class="m-0">you can share and exchange your opinions , inpressions , and emotions</p>
      　<p class="m-0">about various books!</p>

        <div class="btn-wrapper mx-auto col-10">
      　<div class="row">
          <button type="button" class="btn btn-info btn-block btn-sm mb-3">
          <%= link_to 'Log in', new_user_session_path, class: 'text-white' %>
          </button>
        </div>
        <div class="row">
          <button type="button" class="btn btn-success btn-block btn-sm">
          <%= link_to 'Sign up', new_user_registration_path, class: 'text-white' %>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_compile.html.erb
<div class="container">

<div class="text-danger">
<% if new_book.errors.any? %>
  <%= new_book.errors.count%>errors prohibited this obj from being saved:
  <ul>
    <% new_book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>

  <div class="row">
    <div class="col-md-3">
      <h2 class="mt-5">User info</h2>
      <%= image_tag user.get_profile_image('50x50') %>
        <table class="table table-hover">
          <tbody>
            <tr></tr>
            <tr>
              <td>name</td>
              <td><%= user.name %></td>
            </tr>
            <tr>
              <td>introduction</td>
              <td><%= user.introduction %></td>
            </tr>
          </tbody>
        </table>

      <%= link_to edit_user_path(user.id), class: "btn btn-block btn-outline-secondary", method: :get do %>
       <i class="fas fa-user-cog"></i>
      <% end %>


      <h2 class="mt-4">New book</h2>
        <%= form_with model: new_book, local:true do |f| %>
        <div class="form-group">
        <label>Title</label>
        <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
        <label>Opinion</label>
        <%= f.text_area :body, class: "form-control" %>
        </div>

        <%= f.submit 'Create Book', class: "btn btn-success" %>

        <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">
        <div class="container">
        <a class="navbar-brand" href="/">Bookers</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
              <span class="fas fa-home"></span>Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-light' do %>
              <span class="fas fa-users"></span>Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: 'nav-link text-light' do %>
              <span class="fas fa-book-open"></span>Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
              <span class="fas fa-sign-out-alt"></span>Log out
              <% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-light' do %>
              <span class="fas fa-home"></span>Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-light' do %>
              <span class="fas fa-link"></span>About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
              <span class="fas fa-user-plus"></span>Sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
              <span class="fas fa-sign-in-alt"></span>Log in
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>
        </div>
      </nav>
    </header>

    <main class="mb-auto">

        <% if flash[:notice] %>
         <p class="text-success">
           <%= flash[:notice] %>
         </p>
        <% end %>

    <%= yield %>
    </main>

    <footer>
      <div class="container">
        <div class="row">
          <div class="mx-auto xl-col-6">
            <p class="mt-5">CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_side.html.erb
    <div class="container">

    <div class="text-danger">
    <% if new_book.errors.any? %>
      <%= new_book.errors.count%>errors prohibited this obj from being saved:
      <ul>
        <% new_book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    </div>

      <div class="row">
        <div class="col-md-3">
          <h2 class="mt-5">User info</h2>
          <%= image_tag user.get_profile_image('50x50') %>
            <table class="table table-hover">
              <tbody>
                <tr></tr>
                <tr>
                  <td>name</td>
                  <td><%= user.name %></td>
                </tr>
                <tr>
                  <td>introduction</td>
                  <td><%= user.introduction %></td>
                </tr>
                <tr>
                  <td>follow</td>
                  <td><%= link_to following_users.count %></td>
                </tr>
                <tr>
                  <td>follower</td>
                  <td><%= link_to follower_users.count %></td>
                </tr>
              </tbody>
            </table>


          <div>
            <%# if current_user != @user %>
            <% if current_user.following?(@user) %>
            <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-success btn-sm p-1 mb-3"%>
            <% else %>
            <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-primary btn-sm p-1 mb-3" %>
            <% end %>
            <%# end %>
          </div>

          <%= link_to edit_user_path(user.id), class: "btn btn-block btn-outline-secondary", method: :get do %>
           <i class="fas fa-user-cog"></i>
          <% end %>


          <h2 class="mt-4">New book</h2>
            <%= form_with model: new_book, local:true do |f| %>
            <div class="form-group">
            <label>Title</label>
            <%= f.text_field :title, class: "form-control" %>
            </div>
            <div class="form-group">
            <label>Opinion</label>
            <%= f.text_area :body, class: "form-control" %>
            </div>

            <%= f.submit 'Create Book', class: "btn btn-success" %>

            <% end %>

    </div>

app/views/users/edit.html.erb
<div class="container">
    <div class="row">
      <div class="col-8 mx-auto">
        <h2 class="mt-5 mb-4">User info</h2>
        <div class="text-danger">
        <% if @user.errors.any? %>
        <%= @user.errors.count %>errors prohibited this obj from being saved:
        <ul >
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
        <% end %>
        </div>


        <%= form_with model: @user, method: :patch, local:true do |f| %>
        <div class="form-group">
        <label>Name</label>
        <%= f.text_field :name, class: "form-control name" %>
        </div>
        <div class="form-group">
        <label>Image</label>
         <%= f.file_field :profile_image, accept: "image/*" %>
        </div>
        <div class="form-group">
        <label>Introduction</label>
        <%= f.text_area :introduction, class: "form-control" %>
        </div>

        <%= f.submit 'Update User', class: "btn btn-success mb-2" %>

        <% end %>

  </div>
 </div>
</div>

app/views/users/index.html.erb
<!--部分テンプレート-->
<%= render 'side', new_book: @new_book, user: @user, following_users: @following_users, follower_users: @follower_users %>

<div class="col-md-8 offset-md-1">
<h2 class="mt-5">Users</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image('50x50') %></td>
      <td><%= user.name %></td>
      <td><%= link_to 'Show', user_path(user.id) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<!--部分テンプレート-->
<%= render 'side', new_book: @new_book, user: @user, following_users: @following_users, follower_users: @follower_users %>

<div class="col-md-8 offset-md-1">
<h2 class="mt-5">Books</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to book.user do %>
        <%= image_tag book.user.get_profile_image('50x50') %>
        <% end %>
      </td>
      <td><%= link_to book.title, book_path(book.id)  %></td>
      <td><%= book.body %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>